server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
  server:
    password: "${LAVALINK_PASS}"
    sources:
      youtube: false # Using plugin instead
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters: # Enabling all filters
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    ratelimit:
      httpProxy: "socks5://127.0.0.1:4000"
      # strategy: RotateOnBan # Strategy remains disabled for now as proxy is preferred
    #   retryLimit: 5

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - ANDROID_MUSIC
      - TVHTML5_SIMPLY
      - WEB
    oauth:
      enabled: true
      refreshToken: "1//0gL9P_cj-C8uRCgYIARAAGBASNwF-L9Ir5orBep3kN0_gFhp6jEmCwrEDE-d5DqlhiKF9Hc3vmjhIuRNg7QVBCM_sbSXsiqPhpec"
      skipValidation: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

logging:
  file:
    path: ./logs/lavalink.log
  level:
    root: INFO
    lavalink: INFO
